name: Deploy infrastructure

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: infrastructure

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    uses: ajarzyn/Torino/.github/workflows/infrastructure-env.yml@dev
    with:
      ENV_NAME: dev
    secrets:
      AZURE_SUBSCRIPTION: ${{ secrets.DEV_AZURE_SUBSCRIPTION }}
      AZURE_CREDENTIALS: ${{ secrets.DEV_AZURE_CREDENTIALS }}
      DBSA_PASSWORD: ${{ secrets.DEV_DBSA_PASSWORD }}
      DBAPP_PASSWORD: ${{ secrets.DEV_DBAPP_PASSWORD }}
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}

  deploy-test:
    if: github.ref == 'refs/heads/test'
    uses: ajarzyn/Torino/.github/workflows/infrastructure-env.yml@dev
    with:
      ENV_NAME: test
    secrets:
      AZURE_SUBSCRIPTION: ${{ secrets.TEST_AZURE_SUBSCRIPTION }}
      AZURE_CREDENTIALS: ${{ secrets.TEST_AZURE_CREDENTIALS }}
      DBSA_PASSWORD: ${{ secrets.TEST_DBSA_PASSWORD }}
      DBAPP_PASSWORD: ${{ secrets.TEST_DBAPP_PASSWORD }}
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}

  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    uses: ajarzyn/Torino/.github/workflows/infrastructure-env.yml@dev
    with:
      ENV_NAME: prod
    secrets:
      AZURE_SUBSCRIPTION: ${{ secrets.PROD_AZURE_SUBSCRIPTION }}
      AZURE_CREDENTIALS: ${{ secrets.PROD_AZURE_CREDENTIALS }}
      DBSA_PASSWORD: ${{ secrets.PROD_DBSA_PASSWORD }}
      DBAPP_PASSWORD: ${{ secrets.PROD_DBAPP_PASSWORD }}
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
